package com.test.model;

import com.test.model.tbl_stucou;

public interface tbl_stucouMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stucou
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stucou
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int insert(tbl_stucou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stucou
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int insertSelective(tbl_stucou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stucou
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    tbl_stucou selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stucou
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int updateByPrimaryKeySelective(tbl_stucou record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stucou
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int updateByPrimaryKey(tbl_stucou record);
}