package com.test.model;

import com.test.model.tbl_callname;

public interface tbl_callnameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_callname
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_callname
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int insert(tbl_callname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_callname
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int insertSelective(tbl_callname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_callname
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    tbl_callname selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_callname
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int updateByPrimaryKeySelective(tbl_callname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_callname
     *
     * @mbggenerated Mon Apr 02 17:38:14 CST 2018
     */
    int updateByPrimaryKey(tbl_callname record);
}